# Generated by Django 4.0 on 2022-03-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20, verbose_name='name')),
                ('bpub_data', models.DateField(verbose_name='pub date')),
                ('bread', models.IntegerField(default=0, verbose_name='read num')),
                ('bcomment', models.IntegerField(default=0, verbose_name='comment num')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'book',
                'db_table': 'tb_books',
            },
        ),
    ]
